_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 27.9602
  - 2.4519
  - 8
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: ''
source: "tmsource:///Users/kris/Documents/carto2/moabi_transport.tm2source"
styles: 
  - style.mss
  - transport-energy.mss
template: ''
